import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import React from "react";
export const metadata: Metadata = {
  title: "Услуги",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div className="pb-[100px] sm:pb-[300px]">
      <div className="w-[100%] sm:w-[100%] mx-auto relative">
        <div className="absolute top-0 left-0 h-[100px] w-[30px] sm:w-[50px] md:w-[70px] lg:w-[100px]">
          <Image
            src={"/botleft.svg"}
            width={100}
            height={100}
            alt={"minLeft"}
          />
        </div>
        <p className="font-semibold text-lightGreey text-[22px] sm:text-[28px] md:text-[35px] lg:text-[65px] text-center pt-6 sm:pt-16">
          Наши услуги
        </p>

        <div className="md:w-[90%] w-[100%] mx-auto mt-12 sm:mt-24 px-4 sm:px-0">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-x-8 gap-y-8">
            <div className="relative card1">
              <div className="relative">
                <Image
                  src={"/card2.svg"}
                  className="w-[100%] h-[100%]"
                  width={100}
                  height={100}
                  alt="card"
                />
                <p className="mt-2 font-semibold text-[18px] sm:text-[22px] text-lightGreey">
                  Небольшие переезды
                </p>
              </div>
              <div className="card1Content">
                <button className="bg-[#1348F9] rounded-lg py-2 px-6 text-white">
                  Забронировать сейчас
                </button>
                <p className="text-[16px] text-white">Подробнее</p>
              </div>
            </div>
            <div className="relative card2">
              <div className="relative">
                <Image
                  src={"/card2.svg"}
                  className="w-[100%] h-[100%]"
                  width={100}
                  height={100}
                  alt="card"
                />
                <p className="mt-2 font-semibold text-[18px] sm:text-[22px] text-lightGreey">
                  Доставка пакетов
                </p>
              </div>
              <div></div>
            </div>
            <div className="relative card3">
              <div className="relative">
                <Image
                  src={"/card3.svg"}
                  className="w-[100%] h-[100%]"
                  width={100}
                  height={100}
                  alt="card"
                />
                <p className="mt-2 font-semibold text-[18px] sm:text-[22px] text-lightGreey">
                  Винтажная мебель
                </p>
              </div>
              <div></div>
            </div>
            <div className="relative card1">
              <div className="relative">
                <Image
                  src={"/card3.svg"}
                  className="w-[100%] h-[100%]"
                  width={100}
                  height={100}
                  alt="card"
                />
                <p className="mt-2 font-semibold text-[18px] sm:text-[22px] text-lightGreey">
                  Небольшие переезды
                </p>
              </div>
              <div className="card1Content">
                <button className="bg-[#1348F9] rounded-lg py-2 px-6 text-white">
                  Забронировать сейчас
                </button>
                <p className="text-[16px] text-white">Подробнее</p>
              </div>
            </div>
            <div className="relative card1">
              <div className="relative">
                <Image
                  src={"/card2.svg"}
                  className="w-[100%] h-[100%]"
                  width={100}
                  height={100}
                  alt="card"
                />
                <p className="mt-2 font-semibold text-[18px] sm:text-[22px] text-lightGreey">
                  Небольшие переезды
                </p>
              </div>
              <div className="card1Content">
                <button className="bg-[#1348F9] rounded-lg py-2 px-6 text-white">
                  Забронировать сейчас
                </button>
                <p className="text-[16px] text-white">Подробнее</p>
              </div>
            </div>
          </div>

          <p className="font-semibold text-lightGreey text-[22px] sm:text-[28px] md:text-[35px] lg:text-[65px] pt-16">
          Наш Блог
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-8 gap-x-8 gap-y-8">
            <div className="h-[480px] relative border rounded-[24px] shadow-xl">
              <div className="relative h-[46%]">
                <Image
                  src={"/blog1.svg"}
                  alt="blog1"
                  fill
                  className="rounded-t-[24px]"
                />
              </div>
              <div className="h-[54%] flex flex-col p-4">
                <p className="text-[17px] text-lightGreey font-normal font-montserrat">
                  03.07.2023
                </p>
                <p className="mt-4 font-semibold text-[18.27px] text-lightGreey">
                  How to make your freight offers more visible
                </p>
                <p className="text-[15.99px] text-lightGreey font-light mt-2 line-clamp-2">
                  Now, with Teleroute, the process is simpler as the more
                  detailed you make…
                </p>
                <div className="absolute bottom-6 right-6">
                  <Link href={"/"}>
                    <p className="text-[#1348F9] text-[17px] font-semibold">
                      Читать далее
                    </p>
                  </Link>
                </div>
              </div>
            </div>

            <div className="h-[480px] relative border rounded-[24px] shadow-xl">
              <div className="relative h-[46%] w-[100%]">
                <Image
                  src={"/blog2.svg"}
                  alt="blog1"
                  fill
                  className="rounded-t-[24px]"
                />
              </div>
              <div className="h-[54%] flex flex-col p-4">
                <p className="text-[17px] text-lightGreey font-normal font-montserrat">
                  03.07.2023
                </p>
                <p className="mt-4 font-semibold text-[18.27px] text-lightGreey">
                  How to make your freight offers more visible
                </p>
                <p className="text-[15.99px] text-lightGreey font-light mt-2 line-clamp-2">
                  Now, with Teleroute, the process is simpler as the more
                  detailed you make…
                </p>
                <div className="absolute bottom-6 right-6">
                  <Link href={"/"}>
                    <p className="text-[#1348F9] text-[17px] font-semibold">
                      Читать далее
                    </p>
                  </Link>
                </div>
              </div>
            </div>

            <div className="h-[480px] relative border rounded-[24px] shadow-xl">
              <div className="relative h-[46%] w-[100%]">
                <Image
                  src={"/blog3.svg"}
                  alt="blog1"
                  fill
                  className="rounded-t-[24px]"
                />
              </div>
              <div className="h-[54%] flex flex-col p-4">
                <p className="text-[17px] text-lightGreey font-normal font-montserrat">
                  03.07.2023
                </p>
                <p className="mt-4 font-semibold text-[18.27px] text-lightGreey">
                  How to make your freight offers more visible
                </p>
                <p className="text-[15.99px] text-lightGreey font-light mt-2 line-clamp-2">
                  Now, with Teleroute, the process is simpler as the more
                  detailed you make…
                </p>
                <div className="absolute bottom-6 right-6">
                  <Link href={"/"}>
                    <p className="text-[#1348F9] text-[17px] font-semibold">
                      Читать далее
                    </p>
                  </Link>
                </div>
              </div>
            </div>

            <div className="h-[480px] relative border rounded-[24px] shadow-xl">
              <div className="relative h-[46%] w-[100%]">
                <Image
                  src={"/blog4.svg"}
                  alt="blog1"
                  fill
                  className="rounded-t-[24px]"
                />
              </div>
              <div className="h-[54%] flex flex-col p-4">
                <p className="text-[17px] text-lightGreey font-normal font-montserrat">
                  03.07.2023
                </p>
                <p className="mt-4 font-semibold text-[18.27px] text-lightGreey">
                  How to make your freight offers more visible
                </p>
                <p className="text-[15.99px] text-lightGreey font-light mt-2 line-clamp-2">
                  Now, with Teleroute, the process is simpler as the more
                  detailed you make…
                </p>
                <div className="absolute bottom-6 right-6">
                  <Link href={"/"}>
                    <p className="text-[#1348F9] text-[17px] font-semibold">
                      Читать далее
                    </p>
                  </Link>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default Page;
