export {default as About } from './about'
export {default as Ask } from './Ask'
export {default as Comments } from './Comments'
export {default as Footer } from './footer'
export {default as Hero } from './hero'
export {default as Hero2 } from './hero2'
export {default as CustomImage } from './image'
export {default as Navbar } from './navbar'
export {default as Onas } from './onas'
export {default as Send } from './send'
export {default as Sponsr } from './sponsr'
export {default as HorizontalLinearStepper} from './Stepper'