export {default as About } from './about'
export {default as Ask } from './Ask'
export {default as Comments } from './Comments'
export {default as Footer } from './footer'
export {default as Hero } from './hero'
export {default as Hero2 } from './hero2'
export {default as CustomImage } from './image'
export {default as Navbar } from './navbar'
export {default as Onas } from './onas'
export {default as Send } from './send'
export {default as Sponsr } from './sponsr'
export {default as Stepper} from './Stepper'
export {default as ToogleSwitch} from './ToggleSwitch'
export {default as Step1} from './step1'
export {default as Step2} from './step2'
export {default as Step3} from './step3'
export {default as Step4} from './step4'
export {default as StepperForm} from './StepperForm'
export {default as Register} from './auth/register'
export {default as Login} from './auth/login'
export {default as ForgotPassword} from './auth/forgot-password'