export {default as About } from './delivery/about'
export {default as Ask } from './delivery/Ask'
export {default as Comments } from './delivery/Comments'
export {default as Footer } from './delivery/footer'
export {default as Hero } from './delivery/hero'
export {default as Hero2 } from './delivery/hero2'
export {default as CustomImage } from './delivery/image'
export {default as Navbar } from './delivery/navbar'
export {default as Onas } from './delivery/onas'
export {default as Send } from './delivery/send'
export {default as Sponsr } from './delivery/sponsr'
export {default as Stepper} from './delivery/Stepper'
export {default as ToogleSwitch} from './delivery/ToggleSwitch'
export {default as Step1} from './delivery/step1'
export {default as Step2} from './delivery/step2'
export {default as Step3} from './delivery/step3'
export {default as Step4} from './delivery/step4'
export {default as StepperForm} from './delivery/StepperForm'
export {default as Register} from './auth/register'
export {default as Login} from './auth/login'
export {default as ForgotPassword} from './auth/forgot-password'
export {default as AdminHeader} from './admin/AdminHeader'
export {default as RatesTable} from './RatesTable'